<div style="text-align: center;">
  <img src="https://github.com/Hack-io-Data/Imagenes/blob/main/01-LogosHackio/logo_naranja@4x.png?raw=true" alt="esquema" />
</div>

In [4]:
import os

In [5]:
datos = os.listdir()
datos

['laboratorio-modulo1-leccion01-break-pass-continue.ipynb',
 'laboratorio-modulo1-leccion01-manejo-errores.ipynb',
 'laboratorio-modulo1-leccion02-clases.ipynb',
 'laboratorio-modulo2-leccion01-numpy.ipynb']

In [7]:
diccioanrio_df = {diccioanrio_df[re.findall("\d{4}", i)[0]] : pd.read_csv(f"..dato/{i}") for i in datos}

diccioanrio_df = {}
for i in datos:
    df = pd.read_csv(i)
    diccioanrio_df[i.spl]


<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\ganad\AppData\Local\Temp\ipykernel_20928\1996085454.py:1: SyntaxWarning: invalid escape sequence '\d'
  diccioanrio_df = {diccioanrio_df[re.findall("\d{4}", i)[0]] : pd.read_csv(f"..dato/{i}") for i in datos}


NameError: name 'diccioanrio_df' is not defined

for i in datos
# Laboratorio de NumPy

#### Ejercicio 1 - Crea un array de 1D con los números del 0 al 9.

In [11]:
!pip install numpy
import numpy as np


[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [25]:
array1_1d = np.arange(0,10,1,dtype=int)
print(array1_1d)

[0 1 2 3 4 5 6 7 8 9]


#### Ejercicio 2 - Convierte un array 1D en un array 2D con 2 filas y 5 columnas.

In [26]:
array2_2d = array1_1d.reshape(2,5)
print(array2_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


#### Ejercicio 3 - Encuentra los índices de los elementos con valor distinto de 0 en el siguiente array: [0, 2, 0, 3, 0, 4, 0].

In [35]:
array3_1d = np.array([0,2,0,3,0,4,0])
type(array3_1d)
array3_1d.ndim
mascara = array3_1d > 0
elementos_filtrados = np.where(array3_1d>0)[0]

    
print(elementos_filtrados)

[1 3 5]


#### Ejercicio 4 - Crea un array 3x3 con valores aleatorios entre 0 y 1.

In [43]:
array_4_3d = np.random.rand(3,3)
array_4_3d


array([[0.08940429, 0.42566369, 0.09581378],
       [0.9519042 , 0.18490498, 0.27425694],
       [0.35346302, 0.44439452, 0.4438402 ]])

#### Ejercicio 5 - Crea un array de 10 números aleatorios y encuentra el valor máximo y mínimo.

In [50]:
array_5_1d = np.random.randint(0,100,(1,10),int)
print(array_5_1d)
print(f"elvalor máximo es {np.max(array_5_1d)}")
print(f"elvalor minimo es {np.min(array_5_1d)}")

[[54 51 40 56 43 34 99  4 15 56]]
elvalor máximo es 99
elvalor minimo es 4


#### Ejercicio 6 - Crea un array de una dimensión e inviértelo. 

In [61]:
array6_1d = np.array([1,2,3,4,5,6,7,8,9])
array6_1d.ndim
array6_1d_inv = array6_1d[::-1]
array6_1d_inv

array([9, 8, 7, 6, 5, 4, 3, 2, 1])


#### Ejercicio 6 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Selecciona el primer `15` del array.

- Selecciona todos los elementos del primer array. 

- Selecciona la última fila del último array


In [84]:
array6_3d = np.arange(1,25,1,dtype=int)
array6_3d = array6_3d.reshape(2,3,4)
print(array6_3d)
#el primer 15
indice_15 = np.where(array6_3d==15)[0]
print(f"el primer 15 está en {indice_15}")
#primer array
primer_array = array6_3d[0]
print(f"el primer array es: {primer_array}")
#ultima fila
ultima_fila = array6_3d[-1,-1]
print(f"la ultima fila es : {ultima_fila}")

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
el primer 15 está en [1]
el primer array es: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
la ultima fila es : [21 22 23 24]



#### Ejercicio 7 - Genera un array tridimensional de dimensiones (3, 2, 5) con valores enteros del 1 al 30.

- Selecciona el subarray que contiene los dos primeros elementos de cada fila del primer array.

- Selecciona el subarray que contiene todas las filas de los dos últimos arrays.


In [99]:
array7_3d = np.arange(1,31,1,dtype=int)
array7_3d = array7_3d.reshape(3,2,5)
print(array7_3d)
#subarray 1
subarray_1 = [int(array7_3d[0,0,0]),int(array7_3d[0,1,0]),int(array7_3d[0,0,1]),int(array7_3d[0,1,1])]
print(f"los dos primeros elementos de cada fila del primer array son {subarray_1}")
subarray_2 = array7_3d[1:3,0:4]
print(f"todos los elementos de las filas de los dos ultimos arrays son: {subarray_2}")


[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]]]
los dos primeros elementos de cada fila del primer array son [1, 6, 2, 7]
todos los elementos de las filas de los dos ultimos arrays son: [[[11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]]]


#### Ejercicio 8 - Genera un array tridimensional de dimensiones (4, 3, 2) con valores enteros del 1 al 24.

- Cambia todos los elementos de la segunda fila del segundo array por `0`.

- Cambia todos los valores del último array a `-1`.


In [111]:
ej8_array3d = np.arange(1,25,1).reshape(4,3,2)
#cambio de los elementos 
ej8_array3d[1,1] = 0

#segundo cambio
ej8_array3d[3,0:4] = -1
print("el nuevo array con los cambios es: ")
print(ej8_array3d)

el nuevo array con los cambios es: 
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 0  0]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[-1 -1]
  [-1 -1]
  [-1 -1]]]



#### Ejercicio 9 - Genera un array tridimensional de dimensiones (2, 4, 3) con valores enteros del -10 al 13.

- Selecciona todos los elementos mayores a `5`.

- Reemplaza todos los elementos negativos por `0`.


In [118]:
ej9_array3d = np.arange(-10,14,1).reshape(2,4,3)
print(ej9_array3d)
mayores_a_5 = ej9_array3d[ej9_array3d > 5]
print(f"los números mayores a 5 son {mayores_a_5}")
#hago el reemplazo:
ej9_array3d[ej9_array3d < 0] = 0
print(f"la matriz cambiada es: {ej9_array3d}")


[[[-10  -9  -8]
  [ -7  -6  -5]
  [ -4  -3  -2]
  [ -1   0   1]]

 [[  2   3   4]
  [  5   6   7]
  [  8   9  10]
  [ 11  12  13]]]
los números mayores a 5 son [ 6  7  8  9 10 11 12 13]
la matriz cambiada es: [[[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  1]]

 [[ 2  3  4]
  [ 5  6  7]
  [ 8  9 10]
  [11 12 13]]]


#### Ejercicio 10 - Genera un array tridimensional de dimensiones (3, 3, 3) con valores enteros del 1 al 27.

- Selecciona el subarray del segundo array que contenga solo las dos primeras columnas.

- Selecciona todos los elementos del tercer array que sean mayores que `20`.


In [134]:
ej10_array3d = np.arange(1,28,1,dtype=int).reshape(3,3,3)
print(ej10_array3d)
#subarray 1
sub1_10 = ej10_array3d[1,0:3,0:2]
print(f"el subarray sería: {sub1_10}")
#elementos mayores a 20
mayores_20 = ej10_array3d[2][ej10_array3d[2] > 20]
print(f"los mayores a 20 del 3 array son: {mayores_20}")

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
el subarray sería: [[10 11]
 [13 14]
 [16 17]]
los mayores a 20 del 3 array son: [21 22 23 24 25 26 27]


#### Ejercicio 11 - Crea un array de 10 números aleatorios y reemplaza los valores máximos y mínimos por 0.

In [156]:
ej11_aleat = np.random.randint(0,100,(1,10))
print(f"el original es: {ej11_aleat}")
ej11_minimo = np.min(ej11_aleat)
ej11_max = np.max(ej11_aleat)
ej11_aleat[ej11_aleat == ej11_max] = 0 
ej11_aleat[ej11_aleat == ej11_minimo] = 0 
print(f"con los cambios es: {ej11_aleat}")

el original es: [[80 84 31 97 65 93 20 39 19 25]]
con los cambios es: [[80 84 31  0 65 93 20 39  0 25]]


#### Ejercicio 12 - Genera un array de 15 números aleatorios enteros entre 1 y 100 y reordénalo en orden ascendente.

In [159]:
ej12_aleatorio = np.random.randint(1,101,(1,15))
print(f"el original es: {ej12_aleatorio}")
ej12_ordenado = np.sort(ej12_aleatorio)
print(f"el reordenado es: {ej12_ordenado}")

el original es: [[ 3 65 58 38 77 39 64 32 10 88 10 68 61 44 92]]
el reordenado es: [[ 3 10 10 32 38 39 44 58 61 64 65 68 77 88 92]]


#### Ejercicio 11 - Calcula la suma de los elementos a lo largo de las filas y columnas en una matriz 4x4.

In [162]:
ej11_4x4 = np.random.randint(1,26,(4,4))
print(ej11_4x4)
suma_filas = np.sum(ej11_4x4, axis = 1)
print(f"la suma de las filas es igual a : {suma_filas}")
suma_col = np.sum(ej11_4x4, axis = 0)
print(f"la suma de las filas es igual a : {suma_col}")

[[ 7  9  5  5]
 [10  8  5 24]
 [21  2  1  2]
 [16 23 17 12]]
la suma de las filas es igual a : [26 47 26 68]
la suma de las filas es igual a : [54 42 28 43]


#### Ejercicio 12 - Crea una matriz de 5x5 con valores en el borde igual a 1 y en el interior igual a 0.

In [172]:
ej12_5x5 = np.random.randint(2,10,(5,5))
print("la original es: ")
print(ej12_5x5)
ej12_5x5[:,0] = 1
ej12_5x5[:,4] = 1
ej12_5x5[:,1:4] = 0
print("la transformada es: ")
print(ej12_5x5)

la original es: 
[[7 9 9 9 2]
 [9 5 8 9 7]
 [9 9 9 5 6]
 [6 6 7 4 3]
 [5 8 6 8 3]]
la transformada es: 
[[1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]]


#### Ejercicio 13 - Calcula la media y la desviación estándar de un array de 10 números aleatorios.

In [176]:
ej13_array = np.random.randint(2,100,(1,10))
print(f"la matriz es: {ej13_array}")
media13 = np.mean(ej13_array)
desv13 = np.std(ej13_array)
print(f"la media es: {media13} y la desv típica es: {desv13}")


la matriz es: [[88 39  5  8 31 87 49 96  6 50]]
la media es: 45.9 y la desv típica es: 33.11932970336205


#### Ejercicio 14 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Transpón el array para intercambiar los ejes de la forma (2, 3, 4) a (4, 3, 2).

- Observa cómo cambian las posiciones de los elementos y sus índices después de la transposición. Explica en una celda de markdown que es lo que ha pasado. 


In [178]:
ej14_array3d = np.arange(1,25,1).reshape(2,3,4)
print("la original es: ")
print(ej14_array3d)
print("la transpuesta es: ")
print(np.transpose(ej14_array3d))


la original es: 
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
la transpuesta es: 
[[[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]

 [[ 4 16]
  [ 8 20]
  [12 24]]]


lo que hace es trasponer los números, las columnas se convierten en arrays, las filas siguen siendo las mismas y las arrays se convierten en columnas.

#### Ejercicio 15 - Genera un array tridimensional de dimensiones (3, 4, 2) con valores enteros del 1 al 24.

- Transpón el array para intercambiar el primer y segundo eje, de manera que la nueva forma del array sea (4, 3, 2).


In [183]:
ej15_array3d = np.arange(1,25,1).reshape(3,4,2)
print("la original es: ")
print(ej15_array3d)
print("la transpuesta es: ")
print(np.transpose(ej15_array3d,(1,0,2)))

la original es: 
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]

 [[17 18]
  [19 20]
  [21 22]
  [23 24]]]
la transpuesta es: 
[[[ 1  2]
  [ 9 10]
  [17 18]]

 [[ 3  4]
  [11 12]
  [19 20]]

 [[ 5  6]
  [13 14]
  [21 22]]

 [[ 7  8]
  [15 16]
  [23 24]]]


#### Ejercicio 16 - Genera un array tridimensional de dimensiones (3, 2, 4) con valores enteros del 1 al 24.

- Realiza una rotación completa de los ejes para convertir la forma original (3, 2, 4) en (4, 3, 2).


In [184]:
ej15_array3d = np.arange(1,25,1).reshape(3,2,4)
print("la original es: ")
print(ej15_array3d)
print("la transpuesta es: ")
print(np.transpose(ej15_array3d,(2,0,1)))

la original es: 
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]
la transpuesta es: 
[[[ 1  5]
  [ 9 13]
  [17 21]]

 [[ 2  6]
  [10 14]
  [18 22]]

 [[ 3  7]
  [11 15]
  [19 23]]

 [[ 4  8]
  [12 16]
  [20 24]]]


#### Ejercicio 17 - Manipulación de Arrays en 3D

- Crea un array tridimensional con dimensiones (3, 4, 5) cuyos elementos sean números enteros aleatorios entre -10 y 10.

- Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Luego, reemplaza los valores de la matriz vacía basada en los valores del primer array bajo las siguientes condiciones:

   - Si el valor es igual a la mediana, se reemplaza por `"M"`.

   - Si el valor es mayor que la mediana, se reemplaza por `"X"`.

   - Si el valor es menor que la mediana, se reemplaza por `"Y"`.

   - Si el valor es igual al máximo, se reemplaza por `"MAX"`.

   - Si el valor es igual al mínimo, se reemplaza por `"MIN"`.


In [200]:
ej17_array3d = np.random.randint(-10,11,(3,4,5))
print("la original es: ")
print(ej17_array3d)
mediana = np.median(ej17_array3d)
minimo = np.min(ej17_array3d)
maximo = np.max(ej17_array3d)

array17_vacio = np.empty(ej17_array3d.shape, dtype=str)
array17_vacio[ej17_array3d == mediana] = "M"
array17_vacio[ej17_array3d == minimo] = "MIN"
array17_vacio[ej17_array3d == maximo] = "MAX"
array17_vacio[ej17_array3d < mediana] = "Y"
array17_vacio[ej17_array3d > mediana] = "X"
print("la transformada es: ")
print(array17_vacio)

la original es: 
[[[  7   6  10   0   5]
  [  5  -1 -10  10   8]
  [ -4   2  -1  -8   6]
  [  4   5  -3  -6 -10]]

 [[ -7  -2   0  -7   5]
  [ -9  -2  -7   8  -8]
  [ -7   4  -5   0  -8]
  [-10   6   5   7  -7]]

 [[  5  10   8  10  10]
  [-10  -9   6  -5  -1]
  [  9  -6   5   9  -3]
  [  2   1  -9 -10  -4]]]
la transformada es: 
[[['X' 'X' 'X' 'M' 'X']
  ['X' 'Y' 'Y' 'X' 'X']
  ['Y' 'X' 'Y' 'Y' 'X']
  ['X' 'X' 'Y' 'Y' 'Y']]

 [['Y' 'Y' 'M' 'Y' 'X']
  ['Y' 'Y' 'Y' 'X' 'Y']
  ['Y' 'X' 'Y' 'M' 'Y']
  ['Y' 'X' 'X' 'X' 'Y']]

 [['X' 'X' 'X' 'X' 'X']
  ['Y' 'Y' 'X' 'Y' 'Y']
  ['X' 'Y' 'X' 'X' 'Y']
  ['X' 'X' 'Y' 'Y' 'Y']]]


#### Ejercicio 18 - Verificación de Filas y Columnas Iguales

Crea un array bidimensional de dimensiones 4x4, escribe un código para determinar si alguna fila es exactamente igual a alguna columna.

**Reglas:**

- No puedes usar funciones predefinidas de NumPy para comparar filas y columnas (`np.array_equal`, etc.).

- Debes resolverlo con estructuras básicas de Python (bucles, condicionales, etc.).

- Debes revisar si hay al menos una fila que coincida exactamente con alguna columna.

**Pistas**:

- Puedes recorrer cada fila y cada columna de la matriz usando bucles.

- Para comparar una fila con una columna, puedes hacerlo elemento por elemento.